#!/usr/bin/env php
<?php

require dirname(__DIR__) . '/vendor/autoload.php';

use Leonidas\Console\Command\MakeHookCommand;
use Symfony\Component\Console\Application;

$app = new Application();

array_map(fn (string $command) => $app->add(new $command), [
  MakeHookCommand::class,
]);

$app->run();
